### ISSUE TITLE
Add "prepend" method

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/strings#27]
Add a new `.prepend(...values)` method that prepends the given values onto the string:

**Example**

```js
Str('awesome').prepend('Supercharge ', 'is ').get()

// 'Supercharge is awesome'
```

**Comment by satwik-chowdary** [comment]
May I know how many values does it take

**Comment by marcuspoehls** [comment]
As many as the user provides. I suggest using the spread operator collecting all provided values into a single array.

**Comment by satwik-chowdary** [comment]
> As many as the user provides. I suggest using the spread operator collecting all provided values into a single array.

Hmm okay. Can I do it as a part of Hacktoberfest?

**Comment by marcuspoehls** [comment]
Sure!

**Comment by satwik-chowdary** [comment]
> Sure!

Thanks!!

**Comment by cnp96** [comment]
@marcuspoehls Please help review this PR #38
