### ISSUE TITLE
Add "append" method

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/strings#28]
Add a new `.append(...values)` method that appends the given values to the string:

**Example**

```js
Str('Supercharge').append(' is', ' awesome').get()

// 'Supercharge is awesome'
```

**Comment by Rookie3109** [comment]
Can I work on this for hacktoberfest?

**Comment by marcuspoehls** [comment]
Yeah sure 👍

**Comment by cnp96** [comment]
@marcuspoehls Please help review this PR #37
