### ISSUE TITLE
Add "afterLast" method

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/strings#29]
Add a new `.afterLast(delimiter)` method that returns everything from the string after the last occurrence of the given `delimiter`. This method returns the entire string if the delimiter doesn’t exist in the string.

**Example**

```js
Str('Supercharge-is-awesome').afterLast('-').get()

// 'awesome'
```

**Comment by ErikMichelson** [comment]
Hi, I would like to work on this. 👋
