### ISSUE TITLE
Add "beforeLast" method

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/strings#30]
Add a new `.beforeLast(delimiter)` method that returns everything from the string before the last occurrence of the given `delimiter`. This method returns the entire string if the delimiter doesn’t exist in the string.

**Example**

```js
Str('Supercharge-is-awesome').beforeLast('-').get()

// 'Supercharge-is'
```

**Comment by ErikMichelson** [comment]
Hi, I would like to work on this. 👋
