### ISSUE TITLE
Add "replace" method

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/strings#31]
Add a new `.replace(search, replace)` method that replaces the first occurrence of the given `search` value with the replacing `value`.

**Example**

```js
Str('Supercharge is nice').replace('nice', 'sweet').get()

// 'Supercharge is sweet'
```

**Comment by jebitok-dev** [comment]
I'm interested in contributing to this issue

**Comment by marcuspoehls** [comment]
@jebitok-dev Cool! I appreciate your help. Please send a pull request 👍 😃

**Comment by jabbar86** [comment]
@marcuspoehls https://github.com/supercharge/strings/pull/34 pls review
