### ISSUE TITLE
Add replaceLast Method

### ISSUE THREAD

**Issue by jabbar86** [supercharge/strings#35]
The search method returns the position of the first occurrence of a specified text in a string

@marcuspoehls can you assign this to me and add label as `hactoberfest`.

**Comment by marcuspoehls** [comment]
@jabbar86 Hey Jabbar, I feel like the name of the `.search` function my be misleading. My gut feeling tells me to name the function like `.indexOf`. What do you think? You can also check the MDN docs if a similar method exists on JavaScript's global String class

**Comment by jabbar86** [comment]
@marcuspoehls https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/search

**Comment by jabbar86** [comment]
@marcuspoehls I prefer `indexof` over `search`. Let me know your thoughts

**Comment by jabbar86** [comment]
@marcuspoehls any update ?

**Comment by marcuspoehls** [comment]
@jabbar86  I'm not sure if I would merge a pull request for a search into the code base.

What I would like to see instead is a `.replaceLast(search, value)` method replacing the last occurrence of `search` with `value` in a given string.

**Comment by memonjabbar** [comment]
@marcuspoehls i will work on it. Thanks 😁

**Comment by jabbar86** [comment]
@marcuspoehls i will work on it.Thanks :)

**Comment by marcuspoehls** [comment]
@jabbar86 Cool, thank you!

**Comment by cnp96** [comment]
@marcuspoehls I see that this issue is still not updated. If it's not taken right now, I'd like to open a PR.

**Comment by cnp96** [comment]
@marcuspoehls Also, do you mind adding the `hactoberfest` label?

**Comment by marcuspoehls** [comment]
@jabbar86 Hey Jabbar, I didn’t forget you proposed this addition to the library. I’ll favor your pull request if you want to submit one 😃 Are you still interested in this feature?

**Comment by jabbar86** [comment]
@marcuspoehls Yaaa I was caught up in something else. But I am willing to send PR latest by tomorrow if you allow.

**Comment by marcuspoehls** [comment]
@jabbar86 For sure!
