### ISSUE TITLE
Add method: at

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/strings#49]
Implement an `at` method that returns the character at a given `index`.

### Requirements
- please follow the [`proposal for an `at` method](https://github.com/tc39/proposal-relative-indexing-method)
- please use the prepared [`method-at` branch (contains tests)](https://github.com/supercharge/strings/compare/main...method-at)
- make sure the automated tests pass

**Comment by aitorres** [comment]
Hiyya! I can work on this issue if it sounds okay :-)
