### ISSUE TITLE
Add method: isUuid

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/strings#50]
Implement an `isUuid` method that returns true if the wrapped string value is a valid UUID. Returns false otherwise

### Requirements
- we already use the [uuid](https://github.com/uuidjs/uuid) package that exposes a `validate` function. You may reuse the available helper function
- please use the prepared [`method-is-uuid` branch (contains tests)](https://github.com/supercharge/strings/compare/main...method-is-uuid)
- make sure the automated tests pass

**Comment by sprakash57** [comment]
I can do this. Would you mind if I take this up?

**Comment by marcuspoehls** [comment]
@sprakash57 Hey Sunny, sure! I appreciate a pull request 😊

**Comment by marcuspoehls** [comment]
closed by #52
