### ISSUE TITLE
Add method: isSymbol

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/strings#51]
Implement a static `isSymbol` method that returns true if the given value is a JavaScript `Symbol`. Returns false otherwise.

### Requirements
- please use the prepared [`method-is-symbol` branch (contains tests and extended interfaces)](https://github.com/supercharge/strings/compare/main...method-is-symbol)
- make sure the automated tests pass

**Comment by sprakash57** [comment]
May I take this one as well?

**Comment by marcuspoehls** [comment]
@sprakash57 Hey Sunny, I would like to give other developers a chance for contributions. I mean, you can surely go ahead and create a pull request. If you submit a pull request, I’ll wait for a while if someone else is submitting a pull request. I will prefer their contribution then.

At this point, I want to support any Hacktoberfest participants 😃

**Comment by sprakash57** [comment]
Sure, Marcus.

**Comment by g-traub** [comment]
Hello @marcuspoehls, can I work on this issue ?

**Comment by marcuspoehls** [comment]
@g-traub Sure! 😃

**Comment by marcuspoehls** [comment]
Resolved by #55
