### ISSUE TITLE
Add Method: equalsIgnoreCase

### ISSUE THREAD

**Issue by An0thy** [supercharge/strings#59]
Hello, I think a useful method to add would be one that checks for equality while ignoring the character cases. This would be called something like `equalsIgnoreCase`

Some examples:

```js
Str('SUPERCHARGE').equalsIgnoreCase('supercharge') //true
Str('SuPeRcHaRgE').equalsIgnoreCase('sUpErChArGe') //true
Str('SUPERCHARGE').equalsIgnoreCase('SLOWCHARGE') //false
Str('SuPeR').equalsIgnoreCase('sUpErChArGe') //false
```

If this sounds good I'd love to create a PR

**Comment by marcuspoehls** [comment]
@An0thy Hey Anthony, sounds good. I like your idea. Would be great if you can create a pull request 😊 

I'm recalling your idea making sure I understand it: the new method determines if a given string equals the comparison value by ignoring the casing. Basically `value.toLowerCase() === candidate.toLowerCase()`. Is that correct?

If yes, I like the idea!

**Comment by An0thy** [comment]
Hi @marcuspoehls 

Yup, that is correct. The implementation idea is just to convert to the same case then check as you describe.
