### ISSUE TITLE
Str.random(length) not working 

### ISSUE THREAD

**Issue by Vishnu-yes-i-am** [supercharge/strings#67]
I am using random function to generate a token as shown in the code below 
`const  Str=require('@supercharge/strings);
const token = Str.random(50);
`
but its giving me the error 
TypeError: Str.random is not a function
The  same code was working  when i used it some months before.
Is random function is removed ?

**Comment by Vishnu-yes-i-am** [comment]
resolved

**Comment by marcuspoehls** [comment]
@Vishnu-yes-i-am Hey Vishnu, I’ve recently published version `2.0` which uses a different export. Looks like you found it already :)

```js
const { Str } = require('@supercharge/strings)
```
