### ISSUE TITLE
Add "substr" method

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/strings#7]
The `str.substr(start, length)` method returns the substring of length `length` starting from position `start`.

**Example**

```js
Str('Supercharge').substr(0, 5).get()

// 'Super'
```

**Comment by plantprogrammer** [comment]
Hey. I found your project through searching for 'is:open is:issue label:"good first issue" ' in GitHub. Do you mind if I work on this?

**Comment by marcuspoehls** [comment]
@plantprogrammer That’s awesome 😍 please go ahead, I appreciate your help!

**Comment by marcuspoehls** [comment]
@plantprogrammer Hey Ian, do you need help with this issue? Did you get stuck while working on this?

**Comment by plantprogrammer** [comment]
Hi, @marcuspoehls, I've been meaning to learn more about JavaScript, but didn't have the time. 

I'll see what I can do. Don't worry about waiting for me to address this if you or someone else can address this faster.

**Comment by marcuspoehls** [comment]
@plantprogrammer Ok, thank you for letting me know

**Comment by marcuspoehls** [comment]
@mcvladthegoat Hey Vlad, do you want to take this over?

**Comment by mcvladthegoat** [comment]
@marcuspoehls yes, thx :)
