### ISSUE TITLE
Add "limit" method

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/strings#9]
The `str.limit(limit, end = '…')` method returns the first `limit` characters and ends the limited string with `end`.

**Example**

```js
Str('Supercharge').limit(5, ' ->').get()

// 'Super ->'
```

**Comment by mcvladthegoat** [comment]
Hi @marcuspoehls ! I can do this

**Comment by marcuspoehls** [comment]
@mcvladthegoat Hey Vlad, that's great! Thank you, please go ahead :)
